-- Create promotions table
CREATE TABLE IF NOT EXISTS promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    discount_percent INTEGER NOT NULL CHECK (discount_percent > 0 AND discount_percent <= 100),
    label TEXT,
    expires_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create banners table
CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    button_link TEXT DEFAULT '/shop',
    active BOOLEAN DEFAULT TRUE,
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

-- Policies for public reading
CREATE POLICY "Allow public read-only access to promotions" ON promotions FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access to banners" ON banners FOR SELECT USING (true);

-- Policies for admin service-role (bypass RLS by default, but good to have)
-- Note: Service role already bypasses RLS. These are for authenticated admins if needed later.

-- Optional: Initial data for banners to avoid empty homepage
INSERT INTO banners (title, description, image_url, button_link)
VALUES 
('Importation Express 10J', 'Le meilleur du son européen, chez vous en un temps record. Commandez aujourd''hui, livré en 10 jours.', 'https://images.unsplash.com/photo-1550291652-6ea9114a47b1?q=80&w=800', '/about')
ON CONFLICT DO NOTHING;
